# Generated by Django 4.1.7 on 2023-03-05 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Fandango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegoste',
            name='image',
            field=models.ImageField(blank=True, upload_to='chahuistle/'),
        ),
        migrations.AlterField(
            model_name='pegoste',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='pegoste',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
